### ISSUE TITLE
Attempted to call an undefined method named "getEmail" of class "J4k\OAuth2\Client\Provider\User

### ISSUE THREAD

**Issue by nima-vova** [j4k/oauth2-vkontakte#12]
Hi there, 

I have an issue when using your client in a bundle [knpuniversity/oauth2-client-bundle](https://github.com/knpuniversity/oauth2-client-bundle)

I would like to know how can I retrieve user's email because my code doesn't work and I am getting an error  "Attempted to call an undefined method named "getEmail" of class J4k\OAuth2\Client\Provider\User"

Below is a snippet of code which I am using:
$client = $this->get('oauth2.registry')
            ->getClient('vkontakte');
            $user= $client->fetchUser();
            $user->getEmail();

From error message I see that method getEmail() is not exists.

Can you point me which method should I use or what I am doing wrong?

**Comment by j4k** [comment]
https://vk.com/dev/fields

Not entirely sure vk gives back an email address?

**Comment by nima-vova** [comment]
thank you, really no email address
