### ISSUE TITLE
Only variables should be passed by reference

### ISSUE THREAD

**Issue by DonPrus** [j4k/oauth2-vkontakte#8]
I try to get User from token, that another client give to my api.
`$response = $this->oauth->usersGet([],$token,['user_ids' => []]);`
`$response = array_pop($response);`

But get:
<b>Notice</b>:  Only variables should be passed by reference in
<b>/srv/avito/vendor/j4k/oauth2-vkontakte/src/Vkontakte.php</b> on line
<b>143</b>
And after that user info. May be I do smth wrong?

**Comment by j4k** [comment]
Hi, a fix was merged into master a few days ago for this, require that temporarily until I tag a release

**Comment by j4k** [comment]
1.1.1 has the fix in, use that :)
